(deftheme my-spacemacs-dark
  "Created 2023-03-04.")

(custom-theme-set-variables
 'my-spacemacs-dark
 '(ansi-color-names-vector ["#0a0814" "#f2241f" "#67b11d" "#b1951d" "#4f97d7" "#a31db1" "#28def0" "#b2b2b2"])
 '(hl-todo-keyword-faces ''(("TODO" . "#dc752f") ("NEXT" . "#dc752f") ("THEM" . "#2d9574") ("PROG" . "#4f97d7") ("OKAY" . "#4f97d7") ("DONT" . "#f2241f") ("FAIL" . "#f2241f") ("DONE" . "#86dc2f") ("NOTE" . "#b1951d") ("KLUDGE" . "#b1951d") ("HACK" . "#b1951d") ("TEMP" . "#b1951d") ("FIXME" . "#dc752f") ("XXX+" . "#dc752f") ("\\?\\?\\?+" . "#dc752f")))
 '(org-fontify-done-headline nil)
 '(org-fontify-todo-headline nil)
 '(pdf-view-midnight-colors ''("#b2b2b2" . "gray8")))

(custom-theme-set-faces
 'my-spacemacs-dark
 '(cursor ((((class color) (min-colors 89)) (:background "#e3dedd"))))
 '(custom-button ((((class color) (min-colors 89)) :background "#212026" :foreground "#b2b2b2" :box (:line-width 2 :style released-button))))
 '(default-italic ((((class color) (min-colors 89)) (:italic t))))
 '(error ((((class color) (min-colors 89)) (:foreground "#e0211d"))))
 '(eval-sexp-fu-flash ((((class color) (min-colors 89)) (:background "#86dc2f" :foreground "gray8"))))
 '(eval-sexp-fu-flash-error ((((class color) (min-colors 89)) (:background "#e0211d" :foreground "gray8"))))
 '(font-lock-builtin-face ((((class color) (min-colors 89)) (:foreground "#4f97d7"))))
 '(font-lock-comment-face ((((class color) (min-colors 89)) (:foreground "#2aa1ae" :background "#292e34" :slant normal))))
 '(font-lock-constant-face ((((class color) (min-colors 89)) (:foreground "#a45bad"))))
 '(font-lock-doc-face ((((class color) (min-colors 89)) (:foreground "#9f8766"))))
 '(font-lock-function-name-face ((((class color) (min-colors 89)) (:foreground "#bc6ec5" :inherit bold))))
 '(font-lock-keyword-face ((((class color) (min-colors 89)) (:inherit bold :foreground "#4f97d7" :slant normal))))
 '(font-lock-negation-char-face ((((class color) (min-colors 89)) (:foreground "#a45bad"))))
 '(font-lock-preprocessor-face ((((class color) (min-colors 89)) (:foreground "#bc6ec5"))))
 '(font-lock-reference-face ((((class color) (min-colors 89)) (:foreground "#a45bad"))))
 '(font-lock-string-face ((((class color) (min-colors 89)) (:foreground "#2d9574"))))
 '(font-lock-type-face ((((class color) (min-colors 89)) (:foreground "#ce537a" :inherit bold))))
 '(font-lock-variable-name-face ((((class color) (min-colors 89)) (:foreground "#7590db"))))
 '(font-lock-warning-face ((((class color) (min-colors 89)) (:foreground "#dc752f" :background "gray8"))))
 '(fringe ((((class color) (min-colors 89)) (:background "gray8" :foreground "#b2b2b2"))))
 '(header-line ((((class color) (min-colors 89)) :background "#212026")))
 '(highlight ((((class color) (min-colors 89)) (:foreground "#b2b2b2" :background "#444155"))))
 '(hl-line ((((class color) (min-colors 89)) (:background "#212026" :extend t))))
 '(isearch ((((class color) (min-colors 89)) (:foreground "gray8" :background "#86dc2f"))))
 '(lazy-highlight ((((class color) (min-colors 89)) (:background "#29422d" :weight normal))))
 '(link ((((class color) (min-colors 89)) (:foreground "#2aa1ae" :underline t))))
 '(link-visited ((((class color) (min-colors 89)) (:foreground "#c56ec3" :underline t))))
 '(match ((((class color) (min-colors 89)) (:background "#444155" :foreground "#86dc2f"))))
 '(minibuffer-prompt ((((class color) (min-colors 89)) (:inherit bold :foreground "#4f97d7"))))
 '(page-break-lines ((((class color) (min-colors 89)) (:foreground "#5d4d7a"))))
 '(region ((((class color) (min-colors 89)) (:background "#444155" :extend t))))
 '(secondary-selection ((((class color) (min-colors 89)) (:background "#100a14"))))
 '(shadow ((((class color) (min-colors 89)) (:foreground "#686868"))))
 '(success ((((class color) (min-colors 89)) (:foreground "#86dc2f"))))
 '(tooltip ((((class color) (min-colors 89)) (:background "#5e5079" :foreground "#b2b2b2" :bold nil :italic nil :underline nil))))
 '(vertical-border ((((class color) (min-colors 89)) (:foreground "#5d4d7a"))))
 '(warning ((((class color) (min-colors 89)) (:foreground "#dc752f"))))
 '(widget-button-pressed ((((class color) (min-colors 89)) (:foreground "#67b11d"))))
 '(aw-leading-char-face ((((class color) (min-colors 89)) (:foreground "#bc6ec5" :weight bold :height 2.0 :box (:line-width 1 :color "#4f97d7" :style released-button)))))
 '(ahs-face ((((class color) (min-colors 89)) (:background "#444155"))))
 '(ahs-face-unfocused ((((class color) (min-colors 89)) (:background "#444155"))))
 '(ahs-definition-face ((((class color) (min-colors 89)) (:background "#444155"))))
 '(ahs-definition-face-unfocused ((((class color) (min-colors 89)) (:background "#444155"))))
 '(ahs-plugin-whole-buffer-face ((((class color) (min-colors 89)) (:background "#86dc2f" :foreground "gray8"))))
 '(ahs-plugin-default-face ((((class color) (min-colors 89)) (:background "#444155"))))
 '(ahs-plugin-default-face-unfocused ((((class color) (min-colors 89)) (:background "#444155"))))
 '(ansi-color-black ((((class color) (min-colors 89)) (:background "#0a0814" :foreground "#0a0814"))))
 '(ansi-color-red ((((class color) (min-colors 89)) (:background "#f2241f" :foreground "#f2241f"))))
 '(ansi-color-green ((((class color) (min-colors 89)) (:background "#67b11d" :foreground "#67b11d"))))
 '(ansi-color-yellow ((((class color) (min-colors 89)) (:background "#b1951d" :foreground "#b1951d"))))
 '(ansi-color-blue ((((class color) (min-colors 89)) (:background "#4f97d7" :foreground "#4f97d7"))))
 '(ansi-color-magenta ((((class color) (min-colors 89)) (:background "#a31db1" :foreground "#a31db1"))))
 '(ansi-color-cyan ((((class color) (min-colors 89)) (:background "#28def0" :foreground "#28def0"))))
 '(ansi-color-gray ((((class color) (min-colors 89)) (:background "#b2b2b2" :foreground "#b2b2b2"))))
 '(anzu-mode-line ((((class color) (min-colors 89)) (:foreground "#b1951d" :inherit bold))))
 '(ac-completion-face ((((class color) (min-colors 89)) (:underline t :foreground "#4f97d7"))))
 '(avy-lead-face ((((class color) (min-colors 89)) (:background "#293235" :foreground "#67b11d"))))
 '(avy-lead-face-0 ((((class color) (min-colors 89)) (:background "#293235" :foreground "#b1951d"))))
 '(avy-lead-face-1 ((((class color) (min-colors 89)) (:background "#293235" :foreground "#a31db1"))))
 '(avy-lead-face-2 ((((class color) (min-colors 89)) (:background "#293235" :foreground "#4f97d7"))))
 '(cfw:face-title ((((class color) (min-colors 89)) (:foreground "#4f97d7" :height 2.0 :weight bold :inherit variable-pitch))))
 '(cfw:face-header ((((class color) (min-colors 89)) (:foreground "#b2b2b2" :weight bold))))
 '(cfw:face-saturday ((((class color) (min-colors 89)) (:foreground "#b2b2b2" :weight bold))))
 '(cfw:face-sunday ((((class color) (min-colors 89)) (:foreground "#b2b2b2" :weight bold))))
 '(cfw:face-holiday ((((class color) (min-colors 89)) (:foreground "#4f97d7" :weight bold))))
 '(cfw:face-grid ((((class color) (min-colors 89)) (:foreground "#5d4d7a"))))
 '(cfw:face-default-content ((((class color) (min-colors 89)) (:foreground "#67b11d"))))
 '(cfw:face-periods ((((class color) (min-colors 89)) (:foreground "#28def0"))))
 '(cfw:face-day-title ((((class color) (min-colors 89)) (:background "#293239"))))
 '(cfw:face-default-day ((((class color) (min-colors 89)) (:foreground "#b2b2b2" :weight bold))))
 '(cfw:face-annotation ((((class color) (min-colors 89)) (:foreground "#2d9574"))))
 '(cfw:face-disable ((((class color) (min-colors 89)) (:foreground "#686868"))))
 '(cfw:face-today-title ((((class color) (min-colors 89)) (:background "#4f97d7" :weight bold))))
 '(cfw:face-today ((((class color) (min-colors 89)) (:background "#293239" :weight bold))))
 '(cfw:face-select ((((class color) (min-colors 89)) (:background "#a31db1" :weight bold))))
 '(cfw:face-toolbar ((((class color) (min-colors 89)) (:foreground "#b2b2b2" :background "gray8"))))
 '(cfw:face-toolbar-button-off ((((class color) (min-colors 89)) (:foreground "#b2b2b2" :weight bold))))
 '(cfw:face-toolbar-button-on ((((class color) (min-colors 89)) (:foreground "#b2b2b2" :weight bold))))
 '(centaur-tabs-default ((((class color) (min-colors 89)) (:background "gray8" :foreground "#292b2e"))))
 '(centaur-tabs-selected ((((class color) (min-colors 89)) (:background "gray8" :foreground "#b2b2b2" :weight bold))))
 '(centaur-tabs-unselected ((((class color) (min-colors 89)) (:background "#212026" :foreground "#686868" :weight light))))
 '(centaur-tabs-selected-modified ((((class color) (min-colors 89)) (:background "gray8" :foreground "#4f97d7" :weight bold))))
 '(centaur-tabs-unselected-modified ((((class color) (min-colors 89)) (:background "#212026" :weight light :foreground "#4f97d7"))))
 '(centaur-tabs-active-bar-face ((((class color) (min-colors 89)) (:background "#4f97d7"))))
 '(centaur-tabs-modified-marker-selected ((((class color) (min-colors 89)) (:inherit 'centaur-tabs-selected :foreground "#4f97d7"))))
 '(centaur-tabs-modified-marker-unselected ((((class color) (min-colors 89)) (:inherit 'centaur-tabs-unselected :foreground "#4f97d7"))))
 '(cider-enlightened ((((class color) (min-colors 89)) (:background nil :box (:color "#b1951d" :line-width -1 :style nil) :foreground "#b1951d"))))
 '(cider-enlightened-local ((((class color) (min-colors 89)) (:foreground "#b1951d"))))
 '(cider-fringe-good-face ((((class color) (min-colors 89)) (:foreground "#86dc2f"))))
 '(cider-instrumented-face ((((class color) (min-colors 89)) (:background nil :box (:color "#f2241f" :line-width -1 :style nil) :foreground "#f2241f"))))
 '(cider-result-overlay-face ((((class color) (min-colors 89)) (:background nil :box (:color "#4f97d7" :line-width -1 :style nil) :foreground "#4f97d7"))))
 '(cider-test-error-face ((((class color) (min-colors 89)) (:background "#dc752f" :foreground "gray8"))))
 '(cider-test-failure-face ((((class color) (min-colors 89)) (:background "#e0211d" :foreground "gray8"))))
 '(cider-test-success-face ((((class color) (min-colors 89)) (:background "#86dc2f" :foreground "gray8"))))
 '(cider-traced-face ((((class color) (min-colors 89)) :box (:color "#28def0" :line-width -1 :style nil))))
 '(company-echo-common ((((class color) (min-colors 89)) (:background "#b2b2b2" :foreground "gray8"))))
 '(company-preview ((((class color) (min-colors 89)) (:background "#34323e" :foreground "#9a9aba"))))
 '(company-preview-common ((((class color) (min-colors 89)) (:background "#34323e" :foreground "#b2b2b2"))))
 '(company-preview-search ((((class color) (min-colors 89)) (:inherit match))))
 '(company-tooltip-scrollbar-track ((((class color) (min-colors 89)) (:background "#212026"))))
 '(company-tooltip-scrollbar-thumb ((((class color) (min-colors 89)) (:background "#5d4d7a"))))
 '(company-template-field ((((class color) (min-colors 89)) (:inherit region))))
 '(company-tooltip ((((class color) (min-colors 89)) (:background "#34323e" :foreground "#9a9aba"))))
 '(company-tooltip-annotation ((((class color) (min-colors 89)) (:foreground "#ce537a"))))
 '(company-tooltip-common ((((class color) (min-colors 89)) (:background "#34323e" :foreground "#4f97d7"))))
 '(company-tooltip-common-selection ((((class color) (min-colors 89)) (:foreground "#4f97d7"))))
 '(company-tooltip-mouse ((((class color) (min-colors 89)) (:inherit highlight))))
 '(company-tooltip-search ((((class color) (min-colors 89)) (:inherit match))))
 '(company-tooltip-selection ((((class color) (min-colors 89)) (:background "#5e5079" :foreground "#b2b2b2"))))
 '(diff-added ((((class color) (min-colors 89)) :background nil :foreground "#67b11d" :extend t)))
 '(diff-changed ((((class color) (min-colors 89)) :background nil :foreground "#4f97d7")))
 '(diff-header ((((class color) (min-colors 89)) :background "#373040" :foreground "#bc6ec5" :extend t)))
 '(diff-file-header ((((class color) (min-colors 89)) :background "#373040" :foreground "#cbc1d5" :extend t)))
 '(diff-indicator-added ((((class color) (min-colors 89)) :background nil :foreground "#67b11d" :extend t)))
 '(diff-indicator-changed ((((class color) (min-colors 89)) :background nil :foreground "#4f97d7")))
 '(diff-indicator-removed ((((class color) (min-colors 89)) :background nil :foreground "#f2241f")))
 '(diff-refine-added ((((class color) (min-colors 89)) :background "#67b11d" :foreground "gray8")))
 '(diff-refine-changed ((((class color) (min-colors 89)) :background "#4f97d7" :foreground "gray8")))
 '(diff-refine-removed ((((class color) (min-colors 89)) :background "#f2241f" :foreground "gray8")))
 '(diff-removed ((((class color) (min-colors 89)) :background nil :foreground "#f2241f" :extend t)))
 '(diff-hl-insert ((((class color) (min-colors 89)) :background "#67b11d" :foreground "#67b11d")))
 '(diff-hl-delete ((((class color) (min-colors 89)) :background "#f2241f" :foreground "#f2241f")))
 '(diff-hl-change ((((class color) (min-colors 89)) :background "#4f97d7" :foreground "#4f97d7")))
 '(dired-directory ((((class color) (min-colors 89)) (:foreground "#4f97d7" :background "gray8" :inherit bold))))
 '(dired-flagged ((((class color) (min-colors 89)) (:foreground "#f2241f"))))
 '(dired-header ((((class color) (min-colors 89)) (:foreground "#c56ec3" :inherit bold))))
 '(dired-ignored ((((class color) (min-colors 89)) (:inherit shadow))))
 '(dired-mark ((((class color) (min-colors 89)) (:foreground "#c56ec3" :inherit bold))))
 '(dired-marked ((((class color) (min-colors 89)) (:foreground "#a31db1" :inherit bold))))
 '(dired-perm-write ((((class color) (min-colors 89)) (:foreground "#b2b2b2" :underline t))))
 '(dired-symlink ((((class color) (min-colors 89)) (:foreground "#28def0" :background "gray8" :inherit bold))))
 '(dired-warning ((((class color) (min-colors 89)) (:foreground "#dc752f"))))
 '(doom-modeline-bar ((((class color) (min-colors 89)) (:background "#4f97d7"))))
 '(ediff-current-diff-A ((((class color) (min-colors 89)) (:background "#3c2a2c" :foreground "#f2241f" :extend t))))
 '(ediff-current-diff-Ancestor ((((class color) (min-colors 89)) (:background "#293235" :foreground "#2d9574" :extend t))))
 '(ediff-current-diff-B ((((class color) (min-colors 89)) (:background "#293235" :foreground "#67b11d" :extend t))))
 '(ediff-current-diff-C ((((class color) (min-colors 89)) (:background "#293239" :foreground "#4f97d7" :extend t))))
 '(ediff-even-diff-A ((((class color) (min-colors 89)) (:background "#100a14" :extend t))))
 '(ediff-even-diff-Ancestor ((((class color) (min-colors 89)) (:background "#100a14" :extend t))))
 '(ediff-even-diff-B ((((class color) (min-colors 89)) (:background "#100a14" :extend t))))
 '(ediff-even-diff-C ((((class color) (min-colors 89)) (:background "#100a14" :extend t))))
 '(ediff-fine-diff-A ((((class color) (min-colors 89)) (:background "#f2241f" :foreground "gray8" :extend t))))
 '(ediff-fine-diff-Ancestor ((((class color) (min-colors 89)) (:background nil :inherit bold :extend t))))
 '(ediff-fine-diff-B ((((class color) (min-colors 89)) (:background "#67b11d" :foreground "gray8"))))
 '(ediff-fine-diff-C ((((class color) (min-colors 89)) (:background "#4f97d7" :foreground "gray8"))))
 '(ediff-odd-diff-A ((((class color) (min-colors 89)) (:background "#0a0814" :extend t))))
 '(ediff-odd-diff-Ancestor ((((class color) (min-colors 89)) (:background "#0a0814" :extend t))))
 '(ediff-odd-diff-B ((((class color) (min-colors 89)) (:background "#0a0814" :extend t))))
 '(ediff-odd-diff-C ((((class color) (min-colors 89)) (:background "#0a0814" :extend t))))
 '(ein:cell-input-area ((((class color) (min-colors 89)) (:background "#212026"))))
 '(ein:cell-input-prompt ((((class color) (min-colors 89)) (:foreground "#86dc2f"))))
 '(ein:cell-output-prompt ((((class color) (min-colors 89)) (:foreground "#e0211d"))))
 '(ein:notification-tab-normal ((((class color) (min-colors 89)) (:foreground "#4f97d7"))))
 '(ein:notification-tab-selected ((((class color) (min-colors 89)) (:foreground "#86dc2f" :inherit bold))))
 '(eldoc-highlight-function-argument ((((class color) (min-colors 89)) (:foreground "#86dc2f" :inherit bold))))
 '(elfeed-search-date-face ((((class color) (min-colors 89)) (:foreground "#2d9574"))))
 '(elfeed-search-feed-face ((((class color) (min-colors 89)) (:foreground "#4f97d7"))))
 '(elfeed-search-tag-face ((((class color) (min-colors 89)) (:foreground "#bc6ec5"))))
 '(elfeed-search-title-face ((((class color) (min-colors 89)) (:foreground "#7590db"))))
 '(elfeed-search-unread-title-face ((((class color) (min-colors 89)) (:foreground "#b2b2b2"))))
 '(enh-ruby-op-face ((((class color) (min-colors 89)) (:background "gray8" :foreground "#b2b2b2"))))
 '(enh-ruby-string-delimiter-face ((((class color) (min-colors 89)) (:foreground "#2d9574"))))
 '(erc-input-face ((((class color) (min-colors 89)) (:foreground "#bc6ec5"))))
 '(erc-my-nick-face ((((class color) (min-colors 89)) (:foreground "#4f97d7"))))
 '(erc-nick-default-face ((((class color) (min-colors 89)) (:foreground "#4f97d7"))))
 '(erc-nick-prefix-face ((((class color) (min-colors 89)) (:foreground "#b1951d"))))
 '(erc-notice-face ((((class color) (min-colors 89)) (:foreground "#2d9574"))))
 '(erc-prompt-face ((((class color) (min-colors 89)) (:foreground "#86dc2f" :inherit bold))))
 '(erc-timestamp-face ((((class color) (min-colors 89)) (:foreground "#4f97d7"))))
 '(eshell-ls-archive ((((class color) (min-colors 89)) (:foreground "#f2241f" :inherit bold))))
 '(eshell-ls-backup ((((class color) (min-colors 89)) (:inherit font-lock-comment-face))))
 '(eshell-ls-clutter ((((class color) (min-colors 89)) (:inherit font-lock-comment-face))))
 '(eshell-ls-directory ((((class color) (min-colors 89)) (:foreground "#4f97d7" :inherit bold))))
 '(eshell-ls-executable ((((class color) (min-colors 89)) (:foreground "#86dc2f" :inherit bold))))
 '(eshell-ls-missing ((((class color) (min-colors 89)) (:inherit font-lock-warning-face))))
 '(eshell-ls-product ((((class color) (min-colors 89)) (:inherit font-lock-doc-face))))
 '(eshell-ls-special ((((class color) (min-colors 89)) (:foreground "#b1951d" :inherit bold))))
 '(eshell-ls-symlink ((((class color) (min-colors 89)) (:foreground "#28def0" :inherit bold))))
 '(eshell-ls-unreadable ((((class color) (min-colors 89)) (:foreground "#b2b2b2"))))
 '(eshell-prompt ((((class color) (min-colors 89)) (:foreground "#4f97d7" :inherit bold))))
 '(ess-assignment-face ((((class color) (min-colors 89)) (:foreground "#ce537a" :inherit bold))))
 '(ess-backquoted-face ((((class color) (min-colors 89)) (:foreground "#7590db"))))
 '(ess-constant-face ((((class color) (min-colors 89)) (:inherit font-lock-constant-face))))
 '(ess-f-t-face ((((class color) (min-colors 89)) (:inherit font-lock-constant-face))))
 '(ess-function-call-face ((((class color) (min-colors 89)) (:foreground "#bc6ec5"))))
 '(ess-keyword-face ((((class color) (min-colors 89)) (:inherit font-lock-keyword-face))))
 '(ess-matrix-face ((((class color) (min-colors 89)) (:foreground "#686868"))))
 '(ess-modifiers-face ((((class color) (min-colors 89)) (:foreground "#4f97d7"))))
 '(ess-numbers-face ((((class color) (min-colors 89)) (:inherit font-lock-constant-face))))
 '(ess-operator-face ((((class color) (min-colors 89)) (:foreground "#7590db"))))
 '(ess-paren-face ((((class color) (min-colors 89)) (:foreground "#4f97d7"))))
 '(ess-r-control-flow-keyword-face ((((class color) (min-colors 89)) (:foreground "#4f97d7"))))
 '(ess-r-signal-keyword-face ((((class color) (min-colors 89)) (:foreground "#dc752f"))))
 '(evil-ex-lazy-highlight ((((class color) (min-colors 89)) (:background "#86dc2f" :foreground "gray8"))))
 '(evil-ex-substitute-matches ((((class color) (min-colors 89)) (:background "#3c2a2c" :foreground "#f2241f"))))
 '(evil-ex-substitute-replacement ((((class color) (min-colors 89)) (:background "#293235" :foreground "#67b11d"))))
 '(evil-goggles--pulse-face ((((class color) (min-colors 89)) (:background "#32322c" :foreground "#b1951d"))))
 '(evil-goggles-change-face ((((class color) (min-colors 89)) (:background "#2d4252" :foreground "#4f97d7"))))
 '(evil-goggles-commentary-face ((((class color) (min-colors 89)) (:background "#293235" :foreground "#2d9574"))))
 '(evil-goggles-delete-face ((((class color) (min-colors 89)) (:background "#512e31" :foreground "#f2241f"))))
 '(evil-goggles-fill-and-move-face ((((class color) (min-colors 89)) (:background "#29422d" :foreground "#67b11d"))))
 '(evil-goggles-indent-face ((((class color) (min-colors 89)) (:background "#29422d" :foreground "#67b11d"))))
 '(evil-goggles-join-face ((((class color) (min-colors 89)) (:background "#29422d" :foreground "#67b11d"))))
 '(evil-goggles-nerd-commenter-face ((((class color) (min-colors 89)) (:background "#293235" :foreground "#2d9574"))))
 '(evil-goggles-paste-face ((((class color) (min-colors 89)) (:background "#29422d" :foreground "#67b11d"))))
 '(evil-goggles-record-macro-face ((((class color) (min-colors 89)) (:background "#2d4252" :foreground "#4f97d7"))))
 '(evil-goggles-replace-with-register-face ((((class color) (min-colors 89)) (:background "#32322c" :foreground "#b1951d"))))
 '(evil-goggles-set-marker-face ((((class color) (min-colors 89)) (:background "#2d4252" :foreground "#4f97d7"))))
 '(evil-goggles-shift-face ((((class color) (min-colors 89)) (:background "#2d4252" :foreground "#4f97d7"))))
 '(evil-goggles-surround-face ((((class color) (min-colors 89)) (:background "#2d4252" :foreground "#4f97d7"))))
 '(evil-goggles-yank-face ((((class color) (min-colors 89)) (:background "#2d4252" :foreground "#4f97d7"))))
 '(evil-goggles-undo-redo-add-face ((((class color) (min-colors 89)) (:background "#29422d" :foreground "#67b11d"))))
 '(evil-goggles-undo-redo-change-face ((((class color) (min-colors 89)) (:background "#2d4252" :foreground "#4f97d7"))))
 '(evil-goggles-undo-redo-remove-face ((((class color) (min-colors 89)) (:background "#512e31" :foreground "#f2241f"))))
 '(evil-mc-cursor-bar-face ((((class color) (min-colors 89)) (:foreground "#2d9574"))))
 '(evil-mc-cursor-default-face ((((class color) (min-colors 89)) (:background "#2d9574" :foreground "#0a0814"))))
 '(evil-mc-cursor-hbar-face ((((class color) (min-colors 89)) (:foreground "#2d9574"))))
 '(evil-mc-region-face ((((class color) (min-colors 89)) (:inherit highlight))))
 '(flycheck-error ((((supports :underline (:style line)) (class color) (min-colors 89)) (:underline (:style line :color "#e0211d"))) (((class color) (min-colors 89)) (:foreground "#b2b2b2" :background "#e0211d" :inherit bold :underline t))))
 '(flycheck-error-list-checker-name ((((class color) (min-colors 89)) (:foreground "#4f97d7"))))
 '(flycheck-fringe-error ((((class color) (min-colors 89)) (:foreground "#e0211d" :inherit bold))))
 '(flycheck-fringe-info ((((class color) (min-colors 89)) (:foreground "#4f97d7" :inherit bold))))
 '(flycheck-fringe-warning ((((class color) (min-colors 89)) (:foreground "#dc752f" :inherit bold))))
 '(flycheck-info ((((supports :underline (:style line)) (class color) (min-colors 89)) (:underline (:style line :color "#4f97d7"))) (((class color) (min-colors 89)) (:foreground "#b2b2b2" :background "#4f97d7" :inherit bold :underline t))))
 '(flycheck-warning ((((supports :underline (:style line)) (class color) (min-colors 89)) (:underline (:style line :color "#dc752f"))) (((class color) (min-colors 89)) (:foreground "#b2b2b2" :background "#dc752f" :inherit bold :underline t))))
 '(flymake-error ((((supports :underline (:style line)) (class color) (min-colors 89)) (:underline (:style line :color "#e0211d"))) (((class color) (min-colors 89)) (:foreground "#b2b2b2" :background "#e0211d" :inherit bold :underline t))))
 '(flymake-note ((((supports :underline (:style line)) (class color) (min-colors 89)) (:underline (:style wave :color "#4f97d7"))) (((class color) (min-colors 89)) (:foreground "#b2b2b2" :background "#4f97d7" :inherit bold :underline t))))
 '(flymake-warning ((((supports :underline (:style line)) (class color) (min-colors 89)) (:underline (:style line :color "#dc752f"))) (((class color) (min-colors 89)) (:foreground "#b2b2b2" :background "#dc752f" :inherit bold :underline t))))
 '(flyspell-incorrect ((((supports :underline (:style line)) (class color) (min-colors 89)) (:underline (:style wave :color "#dc752f"))) (((class color) (min-colors 89)) (:foreground "#b2b2b2" :background "#dc752f" :inherit bold :underline t))))
 '(flyspell-duplicate ((((supports :underline (:style line)) (class color) (min-colors 89)) (:underline (:style wave :color "#4f97d7"))) (((class color) (min-colors 89)) (:foreground "#b2b2b2" :background "#4f97d7" :inherit bold :underline t))))
 '(jabber-activity-face ((((class color) (min-colors 89)) (:inherit bold :foreground "#f2241f"))))
 '(jabber-activity-personal-face ((((class color) (min-colors 89)) (:inherit bold :foreground "#4f97d7"))))
 '(jabber-chat-error ((((class color) (min-colors 89)) (:inherit bold :foreground "#f2241f"))))
 '(jabber-chat-prompt-foreign ((((class color) (min-colors 89)) (:inherit bold :foreground "#f2241f"))))
 '(jabber-chat-prompt-local ((((class color) (min-colors 89)) (:inherit bold :foreground "#4f97d7"))))
 '(jabber-chat-prompt-system ((((class color) (min-colors 89)) (:inherit bold :foreground "#67b11d"))))
 '(jabber-chat-text-foreign ((((class color) (min-colors 89)) (:foreground "#b2b2b2"))))
 '(jabber-chat-text-local ((((class color) (min-colors 89)) (:foreground "#b2b2b2"))))
 '(jabber-rare-time-face ((((class color) (min-colors 89)) (:foreground "#67b11d"))))
 '(jabber-roster-user-away ((((class color) (min-colors 89)) (:foreground "#b1951d"))))
 '(jabber-roster-user-chatty ((((class color) (min-colors 89)) (:inherit bold :foreground "#67b11d"))))
 '(jabber-roster-user-dnd ((((class color) (min-colors 89)) (:foreground "#f2241f"))))
 '(jabber-roster-user-error ((((class color) (min-colors 89)) (:foreground "#e0211d"))))
 '(jabber-roster-user-offline ((((class color) (min-colors 89)) (:foreground "#b2b2b2"))))
 '(jabber-roster-user-online ((((class color) (min-colors 89)) (:inherit bold :foreground "#67b11d"))))
 '(jabber-roster-user-xa ((((class color) (min-colors 89)) (:foreground "#2d9574"))))
 '(git-gutter-fr:added ((((class color) (min-colors 89)) (:foreground "#67b11d" :inherit bold))))
 '(git-gutter-fr:deleted ((((class color) (min-colors 89)) (:foreground "#f2241f" :inherit bold))))
 '(git-gutter-fr:modified ((((class color) (min-colors 89)) (:foreground "#4f97d7" :inherit bold))))
 '(git-timemachine-minibuffer-detail-face ((((class color) (min-colors 89)) (:foreground "#4f97d7" :inherit bold :background "#293239"))))
 '(gnus-emphasis-highlight-words ((((class color) (min-colors 89)) (:background "#86dc2f" :foreground "gray8"))))
 '(gnus-header-content ((((class color) (min-colors 89)) (:foreground "#4f97d7"))))
 '(gnus-header-from ((((class color) (min-colors 89)) (:foreground "#7590db"))))
 '(gnus-header-name ((((class color) (min-colors 89)) (:foreground "#c56ec3"))))
 '(gnus-header-subject ((((class color) (min-colors 89)) (:foreground "#bc6ec5" :inherit bold))))
 '(gnus-summary-cancelled ((((class color) (min-colors 89)) (:background "#dc752f" :foreground "gray8"))))
 '(guide-key/highlight-command-face ((((class color) (min-colors 89)) (:foreground "#b2b2b2"))))
 '(guide-key/key-face ((((class color) (min-colors 89)) (:foreground "#4f97d7"))))
 '(guide-key/prefix-command-face ((((class color) (min-colors 89)) (:foreground "#4f97d7" :inherit bold))))
 '(helm-bookmark-directory ((((class color) (min-colors 89)) (:inherit helm-ff-directory))))
 '(helm-bookmark-file ((((class color) (min-colors 89)) (:foreground "#b2b2b2"))))
 '(helm-bookmark-gnus ((((class color) (min-colors 89)) (:foreground "#c56ec3"))))
 '(helm-bookmark-info ((((class color) (min-colors 89)) (:foreground "#c56ec3"))))
 '(helm-bookmark-man ((((class color) (min-colors 89)) (:foreground "#c56ec3"))))
 '(helm-bookmark-w3m ((((class color) (min-colors 89)) (:foreground "#c56ec3"))))
 '(helm-buffer-directory ((((class color) (min-colors 89)) (:foreground "#b2b2b2" :background "gray8"))))
 '(helm-buffer-file ((((class color) (min-colors 89)) (:foreground "#b2b2b2" :background "gray8"))))
 '(helm-buffer-not-saved ((((class color) (min-colors 89)) (:foreground "#c56ec3" :background "gray8"))))
 '(helm-buffer-process ((((class color) (min-colors 89)) (:foreground "#4f97d7" :background "gray8"))))
 '(helm-buffer-saved-out ((((class color) (min-colors 89)) (:foreground "#b2b2b2" :background "gray8"))))
 '(helm-buffer-size ((((class color) (min-colors 89)) (:foreground "#b2b2b2" :background "gray8"))))
 '(helm-candidate-number ((((class color) (min-colors 89)) (:background "gray8" :foreground "#4f97d7" :inherit bold))))
 '(helm-ff-directory ((((class color) (min-colors 89)) (:foreground "#4f97d7" :background "gray8" :inherit bold))))
 '(helm-ff-dotted-directory ((((class color) (min-colors 89)) (:foreground "#4f97d7" :background "gray8" :inherit bold))))
 '(helm-ff-dotted-symlink-directory ((((class color) (min-colors 89)) (:foreground "#28def0" :background "gray8" :inherit bold))))
 '(helm-ff-executable ((((class color) (min-colors 89)) (:foreground "#86dc2f" :background "gray8" :weight normal))))
 '(helm-ff-file ((((class color) (min-colors 89)) (:foreground "#b2b2b2" :background "gray8" :weight normal))))
 '(helm-ff-invalid-symlink ((((class color) (min-colors 89)) (:foreground "#f2241f" :background "gray8" :inherit bold))))
 '(helm-ff-prefix ((((class color) (min-colors 89)) (:foreground "gray8" :background "#4f97d7" :weight normal))))
 '(helm-ff-symlink ((((class color) (min-colors 89)) (:foreground "#28def0" :background "gray8" :inherit bold))))
 '(helm-grep-cmd-line ((((class color) (min-colors 89)) (:foreground "#b2b2b2" :background "gray8"))))
 '(helm-grep-file ((((class color) (min-colors 89)) (:foreground "#b2b2b2" :background "gray8"))))
 '(helm-grep-finish ((((class color) (min-colors 89)) (:foreground "#b2b2b2" :background "gray8"))))
 '(helm-grep-lineno ((((class color) (min-colors 89)) (:foreground "#ce537a" :background "gray8" :inherit bold))))
 '(helm-grep-match ((((class color) (min-colors 89)) (:foreground nil :background nil :inherit helm-match))))
 '(helm-header ((((class color) (min-colors 89)) (:foreground "#b2b2b2" :background "gray8" :underline nil :box nil))))
 '(helm-header-line-left-margin ((((class color) (min-colors 89)) (:foreground "#4f97d7" :background nil))))
 '(helm-match ((((class color) (min-colors 89)) (:background "#293239" :foreground "#4f97d7"))))
 '(helm-match-item ((((class color) (min-colors 89)) (:background "#293239" :foreground "#4f97d7"))))
 '(helm-moccur-buffer ((((class color) (min-colors 89)) (:foreground "#7590db" :background "gray8"))))
 '(helm-selection ((((class color) (min-colors 89)) (:background "#444155"))))
 '(helm-selection-line ((((class color) (min-colors 89)) (:background "#212026"))))
 '(helm-separator ((((class color) (min-colors 89)) (:foreground "#c56ec3" :background "gray8"))))
 '(helm-source-header ((((class color) (min-colors 89)) (:background "#c56ec3" :foreground "gray8" :inherit bold))))
 '(helm-time-zone-current ((((class color) (min-colors 89)) (:foreground "#4f97d7" :background "gray8"))))
 '(helm-time-zone-home ((((class color) (min-colors 89)) (:foreground "#c56ec3" :background "gray8"))))
 '(helm-visible-mark ((((class color) (min-colors 89)) (:foreground "#4f97d7" :background "#100a14"))))
 '(helm-swoop-target-line-block-face ((((class color) (min-colors 89)) (:foreground "#b2b2b2" :background "#444155"))))
 '(helm-swoop-target-line-face ((((class color) (min-colors 89)) (:background "#444155"))))
 '(helm-swoop-target-word-face ((((class color) (min-colors 89)) (:background "#444155" :foreground "#86dc2f"))))
 '(hi-green ((((class color) (min-colors 89)) (:foreground "#67b11d" :background "#293235"))))
 '(hi-yellow ((((class color) (min-colors 89)) (:foreground "#b1951d" :background "#32322c"))))
 '(highlight-indentation-face ((((class color) (min-colors 89)) (:background "#292e34"))))
 '(highlight-symbol-face ((((class color) (min-colors 89)) (:background "#42444a"))))
 '(highlight-thing ((((class color) (min-colors 89)) (:background "#42444a"))))
 '(hydra-face-blue ((((class color) (min-colors 89)) (:foreground "#4f97d7"))))
 '(hydra-face-red ((((class color) (min-colors 89)) (:foreground "#f2241f"))))
 '(ido-first-match ((((class color) (min-colors 89)) (:foreground "#c56ec3" :inherit bold))))
 '(ido-only-match ((((class color) (min-colors 89)) (:foreground "#86dc2f" :inherit bold))))
 '(ido-subdir ((((class color) (min-colors 89)) (:foreground "#4f97d7"))))
 '(ido-vertical-match-face ((((class color) (min-colors 89)) (:foreground "#c56ec3" :underline nil))))
 '(info-header-xref ((((class color) (min-colors 89)) (:foreground "#bc6ec5" :underline t))))
 '(info-menu ((((class color) (min-colors 89)) (:foreground "#86dc2f"))))
 '(info-node ((((class color) (min-colors 89)) (:foreground "#bc6ec5" :inherit bold))))
 '(info-quoted-name ((((class color) (min-colors 89)) (:foreground "#4f97d7"))))
 '(info-reference-item ((((class color) (min-colors 89)) (:background nil :underline t :inherit bold))))
 '(info-string ((((class color) (min-colors 89)) (:foreground "#2d9574"))))
 '(info-title-1 ((((class color) (min-colors 89)) (:height 1.4 :inherit bold))))
 '(info-title-2 ((((class color) (min-colors 89)) (:height 1.3 :inherit bold))))
 '(info-title-3 ((((class color) (min-colors 89)) (:height 1.3))))
 '(info-title-4 ((((class color) (min-colors 89)) (:height 1.2))))
 '(ivy-current-match ((((class color) (min-colors 89)) (:background "#444155" :inherit bold :extend t))))
 '(ivy-minibuffer-match-face-1 ((((class color) (min-colors 89)) (:inherit bold))))
 '(ivy-minibuffer-match-face-2 ((((class color) (min-colors 89)) (:foreground "#4f97d7" :underline t))))
 '(ivy-minibuffer-match-face-3 ((((class color) (min-colors 89)) (:foreground "#b1951d" :underline t))))
 '(ivy-minibuffer-match-face-4 ((((class color) (min-colors 89)) (:foreground "#67b11d" :underline t))))
 '(ivy-remote ((((class color) (min-colors 89)) (:foreground "#28def0"))))
 '(ivy-posframe ((((class color) (min-colors 89)) (:background "#100a14"))))
 '(font-latex-bold-face ((((class color) (min-colors 89)) (:foreground "#c56ec3"))))
 '(font-latex-italic-face ((((class color) (min-colors 89)) (:foreground "#4f97d7" :italic t))))
 '(font-latex-match-reference-keywords ((((class color) (min-colors 89)) (:foreground "#a45bad"))))
 '(font-latex-match-variable-keywords ((((class color) (min-colors 89)) (:foreground "#7590db"))))
 '(font-latex-sectioning-0-face ((((class color) (min-colors 89)) (:inherit bold :foreground "#67b11d" :height 1.3 :background nil))))
 '(font-latex-sectioning-1-face ((((class color) (min-colors 89)) (:inherit bold :foreground "#b1951d" :height 1.3 :background nil))))
 '(font-latex-sectioning-2-face ((((class color) (min-colors 89)) (:inherit bold :foreground "#4f97d7" :height 1.3 :background nil))))
 '(font-latex-sectioning-3-face ((((class color) (min-colors 89)) (:inherit bold :foreground "#2d9574" :height 1.2 :background nil))))
 '(font-latex-sectioning-4-face ((((class color) (min-colors 89)) (:bold nil :foreground "#67b11d" :height 1.1 :background nil))))
 '(font-latex-sectioning-5-face ((((class color) (min-colors 89)) (:bold nil :foreground "#b1951d" :background nil))))
 '(font-latex-string-face ((((class color) (min-colors 89)) (:foreground "#2d9574"))))
 '(font-latex-warning-face ((((class color) (min-colors 89)) (:foreground "#dc752f"))))
 '(ledger-font-directive-face ((((class color) (min-colors 89)) (:foreground "#9f8766"))))
 '(ledger-font-posting-amount-face ((((class color) (min-colors 89)) (:foreground "#b1951d"))))
 '(ledger-font-posting-date-face ((((class color) (min-colors 89)) (:foreground "#4f97d7"))))
 '(ledger-occur-xact-face ((((class color) (min-colors 89)) (:background "#212026"))))
 '(linum ((((class color) (min-colors 89)) (:foreground "#44505c" :background "#212026" :inherit default))))
 '(line-number ((((class color) (min-colors 89)) (:foreground "#44505c" :background "#212026" :inherit default))))
 '(line-number-current-line ((((class color) (min-colors 89)) (:foreground "#b2b2b2" :background "#212026" :inherit line-number))))
 '(linum-relative-current-face ((((class color) (min-colors 89)) (:foreground "#c56ec3"))))
 '(lsp-ui-doc-background ((((class color) (min-colors 89)) (:background "#212026"))))
 '(lsp-ui-doc-header ((((class color) (min-colors 89)) (:foreground "#4f97d7" :background "#293239"))))
 '(lsp-ui-sideline-code-action ((((class color) (min-colors 89)) (:foreground "#c56ec3"))))
 '(magit-blame-culprit ((((class color) (min-colors 89)) :background "#32322c" :foreground "#b1951d")))
 '(magit-blame-date ((((class color) (min-colors 89)) :background "#32322c" :foreground "#67b11d")))
 '(magit-blame-hash ((((class color) (min-colors 89)) :background "#32322c" :foreground "#bc6ec5")))
 '(magit-blame-header ((((class color) (min-colors 89)) :background "#32322c" :foreground "#67b11d")))
 '(magit-blame-heading ((((class color) (min-colors 89)) :background "#32322c" :foreground "#67b11d")))
 '(magit-blame-name ((((class color) (min-colors 89)) :background "#32322c" :foreground "#b1951d")))
 '(magit-blame-sha1 ((((class color) (min-colors 89)) :background "#32322c" :foreground "#bc6ec5")))
 '(magit-blame-subject ((((class color) (min-colors 89)) :background "#32322c" :foreground "#b1951d")))
 '(magit-blame-summary ((((class color) (min-colors 89)) :background "#32322c" :foreground "#b1951d" :extend t)))
 '(magit-blame-time ((((class color) (min-colors 89)) :background "#32322c" :foreground "#67b11d")))
 '(magit-branch ((((class color) (min-colors 89)) (:foreground "#a45bad" :inherit bold))))
 '(magit-branch-current ((((class color) (min-colors 89)) (:background "#293239" :foreground "#4f97d7" :inherit bold :box t))))
 '(magit-branch-local ((((class color) (min-colors 89)) (:background "#293239" :foreground "#4f97d7" :inherit bold))))
 '(magit-branch-remote ((((class color) (min-colors 89)) (:background "#293235" :foreground "#2d9574" :inherit bold))))
 '(magit-diff-context-highlight ((((class color) (min-colors 89)) (:background "#212026" :foreground "#b2b2b2" :extend t))))
 '(magit-diff-hunk-heading ((((class color) (min-colors 89)) (:background "#34323e" :foreground "#9a9aba" :extend t))))
 '(magit-diff-hunk-heading-highlight ((((class color) (min-colors 89)) (:background "#5e5079" :foreground "#b2b2b2" :extend t))))
 '(magit-hash ((((class color) (min-colors 89)) (:foreground "#7590db"))))
 '(magit-hunk-heading ((((class color) (min-colors 89)) (:background "#100a14" :extend t))))
 '(magit-hunk-heading-highlight ((((class color) (min-colors 89)) (:background "#100a14" :extend t))))
 '(magit-item-highlight ((((class color) (min-colors 89)) :background "#212026" :extend t)))
 '(magit-log-author ((((class color) (min-colors 89)) (:foreground "#bc6ec5"))))
 '(magit-log-head-label-head ((((class color) (min-colors 89)) (:background "#b1951d" :foreground "gray8" :inherit bold))))
 '(magit-log-head-label-local ((((class color) (min-colors 89)) (:background "#4f97d7" :foreground "gray8" :inherit bold))))
 '(magit-log-head-label-remote ((((class color) (min-colors 89)) (:background "#86dc2f" :foreground "gray8" :inherit bold))))
 '(magit-log-head-label-tags ((((class color) (min-colors 89)) (:background "#a31db1" :foreground "gray8" :inherit bold))))
 '(magit-log-head-label-wip ((((class color) (min-colors 89)) (:background "#28def0" :foreground "gray8" :inherit bold))))
 '(magit-log-sha1 ((((class color) (min-colors 89)) (:foreground "#2d9574"))))
 '(magit-process-ng ((((class color) (min-colors 89)) (:foreground "#dc752f" :inherit bold))))
 '(magit-process-ok ((((class color) (min-colors 89)) (:foreground "#bc6ec5" :inherit bold))))
 '(magit-reflog-amend ((((class color) (min-colors 89)) (:foreground "#a31db1"))))
 '(magit-reflog-checkout ((((class color) (min-colors 89)) (:foreground "#4f97d7"))))
 '(magit-reflog-cherry-pick ((((class color) (min-colors 89)) (:foreground "#67b11d"))))
 '(magit-reflog-commit ((((class color) (min-colors 89)) (:foreground "#67b11d"))))
 '(magit-reflog-merge ((((class color) (min-colors 89)) (:foreground "#67b11d"))))
 '(magit-reflog-other ((((class color) (min-colors 89)) (:foreground "#28def0"))))
 '(magit-reflog-rebase ((((class color) (min-colors 89)) (:foreground "#a31db1"))))
 '(magit-reflog-remote ((((class color) (min-colors 89)) (:foreground "#28def0"))))
 '(magit-reflog-reset ((((class color) (min-colors 89)) (:foreground "#f2241f"))))
 '(magit-section-heading ((((class color) (min-colors 89)) (:foreground "#4f97d7" :inherit bold :extend t))))
 '(magit-section-highlight ((((class color) (min-colors 89)) (:background "#212026" :extend t))))
 '(magit-section-title ((((class color) (min-colors 89)) (:background "gray8" :foreground "#4f97d7" :inherit bold))))
 '(Man-overstrike ((((class color) (min-colors 89)) (:foreground "#4f97d7" :inherit bold))))
 '(Man-reverse ((((class color) (min-colors 89)) (:foreground "#444155"))))
 '(Man-underline ((((class color) (min-colors 89)) (:foreground "#c56ec3" :underline t))))
 '(markdown-header-face-1 ((((class color) (min-colors 89)) (:inherit bold :foreground "#4f97d7" :height 1.3 :background nil))))
 '(markdown-header-face-2 ((((class color) (min-colors 89)) (:inherit bold :foreground "#2d9574" :height 1.2 :background nil))))
 '(markdown-header-face-3 ((((class color) (min-colors 89)) (:bold nil :foreground "#67b11d" :height 1.1 :background nil))))
 '(markdown-header-face-4 ((((class color) (min-colors 89)) (:bold nil :foreground "#b1951d" :background nil))))
 '(markdown-header-face-5 ((((class color) (min-colors 89)) (:bold nil :foreground "#4f97d7"))))
 '(markdown-header-face-6 ((((class color) (min-colors 89)) (:bold nil :foreground "#2d9574"))))
 '(markdown-table-face ((((class color) (min-colors 89)) (:foreground "#b2b2b2" :background "#293239"))))
 '(mode-line ((((class color) (min-colors 89)) (:foreground "#b2b2b2" :background "#222226" :box (:color "#5d4d7a" :line-width 1)))))
 '(mode-line-buffer-id ((((class color) (min-colors 89)) (:inherit bold :foreground "#bc6ec5"))))
 '(mode-line-inactive ((((class color) (min-colors 89)) (:foreground "#b2b2b2" :background "gray8" :box (:color "#5d4d7a" :line-width 1)))))
 '(mu4e-attach-number-face ((((class color) (min-colors 89)) (:foreground "#7590db"))))
 '(mu4e-cited-1-face ((((class color) (min-colors 89)) (:foreground "#4f97d7"))))
 '(mu4e-cited-2-face ((((class color) (min-colors 89)) (:foreground "#2d9574"))))
 '(mu4e-cited-3-face ((((class color) (min-colors 89)) (:foreground "#67b11d"))))
 '(mu4e-cited-4-face ((((class color) (min-colors 89)) (:foreground "#b1951d"))))
 '(mu4e-cited-5-face ((((class color) (min-colors 89)) (:foreground "#4f97d7"))))
 '(mu4e-cited-6-face ((((class color) (min-colors 89)) (:foreground "#2d9574"))))
 '(mu4e-cited-7-face ((((class color) (min-colors 89)) (:foreground "#67b11d"))))
 '(mu4e-contact-face ((((class color) (min-colors 89)) (:foreground "#bc6ec5"))))
 '(mu4e-draft-face ((((class color) (min-colors 89)) (:foreground "#7590db"))))
 '(mu4e-flagged-face ((((class color) (min-colors 89)) (:foreground "#b1951d" :inherit bold))))
 '(mu4e-header-key-face ((((class color) (min-colors 89)) (:foreground "#9f8766" :inherit bold))))
 '(mu4e-header-title-face ((((class color) (min-colors 89)) (:foreground "#4f97d7" :inherit bold))))
 '(mu4e-header-marks-face ((((class color) (min-colors 89)) (:foreground "#c56ec3"))))
 '(mu4e-header-value-face ((((class color) (min-colors 89)) (:foreground "#4f97d7" :inherit bold))))
 '(mu4e-header-highlight-face ((((class color) (min-colors 89)) (:background "#444155"))))
 '(mu4e-highlight-face ((((class color) (min-colors 89)) (:foreground "#c56ec3"))))
 '(mu4e-title-face ((((class color) (min-colors 89)) (:foreground "#2d9574" :inherit bold))))
 '(mu4e-replied-face ((((class color) (min-colors 89)) (:foreground "#67b11d"))))
 '(mu4e-modeline-face ((((class color) (min-colors 89)) (:foreground "#b1951d"))))
 '(mu4e-special-header-value-face ((((class color) (min-colors 89)) (:foreground "#67b11d"))))
 '(mu4e-unread-face ((((class color) (min-colors 89)) (:foreground "#4f97d7" :inherit bold))))
 '(mu4e-view-url-number-face ((((class color) (min-colors 89)) (:foreground "#c56ec3"))))
 '(mu4e-maildirs-extension-maildir-hl-face ((((class color) (min-colors 89)) (:foreground "#4f97d7" :inherit bold))))
 '(notmuch-search-date ((((class color) (min-colors 89)) (:foreground "#bc6ec5"))))
 '(notmuch-search-flagged-face ((((class color) (min-colors 89)) (:weight extra-bold))))
 '(notmuch-search-non-matching-authors ((((class color) (min-colors 89)) (:foreground "#686868"))))
 '(notmuch-search-unread-face ((((class color) (min-colors 89)) (:background "#3b314d"))))
 '(notmuch-tag-face ((((class color) (min-colors 89)) (:foreground "#4f97d7"))))
 '(notmuch-tag-flagged ((((class color) (min-colors 89)) (:foreground "#dc752f"))))
 '(neo-dir-link-face ((((class color) (min-colors 89)) (:foreground "#4f97d7" :inherit bold))))
 '(neo-expand-btn-face ((((class color) (min-colors 89)) (:foreground "#b2b2b2"))))
 '(neo-file-link-face ((((class color) (min-colors 89)) (:foreground "#b2b2b2"))))
 '(neo-root-dir-face ((((class color) (min-colors 89)) (:foreground "#bc6ec5" :inherit bold))))
 '(org-agenda-clocking ((((class color) (min-colors 89)) (:background "#444155" :foreground "#c56ec3"))))
 '(org-agenda-date ((((class color) (min-colors 89)) (:foreground "#7590db" :height 1.0))))
 '(org-agenda-date-today ((((class color) (min-colors 89)) (:foreground "#4f97d7" :inherit bold :height 1.0))))
 '(org-agenda-date-weekend ((((class color) (min-colors 89)) (:inherit bold :foreground "#7590db"))))
 '(org-agenda-done ((((class color) (min-colors 89)) (:foreground "#86dc2f" :height 1.0))))
 '(org-agenda-structure ((((class color) (min-colors 89)) (:inherit bold :foreground "#c56ec3"))))
 '(org-block ((((class color) (min-colors 89)) (:background "#2f2b33" :foreground "#cbc1d5" :extend t))))
 '(org-block-begin-line ((((class color) (min-colors 89)) (:background "#373040" :foreground "#827591" :extend t))))
 '(org-block-end-line ((((class color) (min-colors 89)) (:background "#373040" :foreground "#827591" :extend t))))
 '(org-clock-overlay ((((class color) (min-colors 89)) (:foreground "#c56ec3"))))
 '(org-code ((((class color) (min-colors 89)) (:foreground "#28def0"))))
 '(org-column ((((class color) (min-colors 89)) (:background "#444155" :inherit default))))
 '(org-column-title ((((class color) (min-colors 89)) (:background "#444155"))))
 '(org-date ((((class color) (min-colors 89)) (:underline t :foreground "#7590db"))))
 '(org-date-selected ((((class color) (min-colors 89)) (:background "#bc6ec5" :foreground "gray8"))))
 '(org-document-info-keyword ((((class color) (min-colors 89)) (:foreground "#9f8766"))))
 '(org-document-title ((((class color) (min-colors 89)) (:foreground "#bc6ec5" :inherit bold :height 1.4 :underline t))))
 '(org-done ((((class color) (min-colors 89)) (:foreground "#86dc2f" :inherit bold :background "gray8"))))
 '(org-ellipsis ((((class color) (min-colors 89)) (:foreground "#4f97d7"))))
 '(org-footnote ((((class color) (min-colors 89)) (:underline t :foreground "#b2b2b2"))))
 '(org-headline-done ((((class color) (min-colors 89)) (:foreground "#2d9574"))))
 '(org-headline-todo ((((class color) (min-colors 89)) (:foreground "#9f8766"))))
 '(org-hide ((((class color) (min-colors 89)) (:foreground "#b2b2b2"))))
 '(org-kbd ((((class color) (min-colors 89)) (:inherit region :foreground "#b2b2b2" :box (:line-width 1 :style released-button)))))
 '(org-level-1 ((((class color) (min-colors 89)) (:inherit bold :bold unspecified :foreground "#4f97d7" :height 1.4 :background nil))))
 '(org-level-2 ((((class color) (min-colors 89)) (:inherit bold :bold unspecified :foreground "#2d9574" :height 1.3 :background nil))))
 '(org-level-3 ((((class color) (min-colors 89)) (:bold nil :foreground "#67b11d" :height 1.2 :background nil))))
 '(org-level-4 ((((class color) (min-colors 89)) (:bold nil :foreground "#b1951d" :height 1.1 :background nil))))
 '(org-level-5 ((((class color) (min-colors 89)) (:bold nil :foreground "#4f97d7"))))
 '(org-level-6 ((((class color) (min-colors 89)) (:bold nil :foreground "#2d9574"))))
 '(org-level-7 ((((class color) (min-colors 89)) (:bold nil :foreground "#67b11d"))))
 '(org-level-8 ((((class color) (min-colors 89)) (:bold nil :foreground "#b1951d"))))
 '(org-link ((((class color) (min-colors 89)) (:underline t :foreground "#2aa1ae"))))
 '(org-meta-line ((((class color) (min-colors 89)) (:foreground "#9f8766"))))
 '(org-mode-line-clock-overrun ((((class color) (min-colors 89)) (:foreground "#e0211d"))))
 '(org-priority ((((class color) (min-colors 89)) (:foreground "#dc752f" :inherit bold :bold unspecified))))
 '(org-quote ((((class color) (min-colors 89)) (:inherit org-block :slant italic))))
 '(org-scheduled ((((class color) (min-colors 89)) (:foreground "#c56ec3"))))
 '(org-scheduled-today ((((class color) (min-colors 89)) (:foreground "#bc6ec5" :height 1.0))))
 '(org-scheduled-previously ((((class color) (min-colors 89)) (:foreground "#b2b2b2" :slant italic))))
 '(org-sexp-date ((((class color) (min-colors 89)) (:foreground "#b2b2b2"))))
 '(org-special-keyword ((((class color) (min-colors 89)) (:foreground "#bc6ec5"))))
 '(org-table ((((class color) (min-colors 89)) (:foreground "#b2b2b2" :background "#293239"))))
 '(org-tag ((((class color) (min-colors 89)) (:foreground "#9f8766"))))
 '(org-time-grid ((((class color) (min-colors 89)) (:foreground "#2d9574"))))
 '(org-todo ((((class color) (min-colors 89)) (:foreground "#dc752f" :inherit bold :background "gray8"))))
 '(org-upcoming-deadline ((((class color) (min-colors 89)) (:foreground "#dc752f" :inherit org-priority))))
 '(org-upcoming-distant-deadline ((((class color) (min-colors 89)) (:foreground "#86dc2f" :inherit org-priority))))
 '(org-verbatim ((((class color) (min-colors 89)) (:foreground "#4f97d7"))))
 '(org-verse ((((class color) (min-colors 89)) (:inherit org-block :slant italic))))
 '(org-warning ((((class color) (min-colors 89)) (:foreground "#e0211d" :inherit org-priority))))
 '(outline-1 ((((class color) (min-colors 89)) (:inherit org-level-1))))
 '(outline-2 ((((class color) (min-colors 89)) (:inherit org-level-2))))
 '(outline-3 ((((class color) (min-colors 89)) (:inherit org-level-3))))
 '(outline-4 ((((class color) (min-colors 89)) (:inherit org-level-4))))
 '(outline-5 ((((class color) (min-colors 89)) (:inherit org-level-5))))
 '(outline-6 ((((class color) (min-colors 89)) (:inherit org-level-6))))
 '(outline-7 ((((class color) (min-colors 89)) (:inherit org-level-7))))
 '(outline-8 ((((class color) (min-colors 89)) (:inherit org-level-8))))
 '(parinfer-pretty-parens:dim-paren-face ((((class color) (min-colors 89)) (:foreground "#686868"))))
 '(parinfer-rust-dim-parens ((((class color) (min-colors 89)) (:foreground "#686868"))))
 '(persp-selected-face ((((class color) (min-colors 89)) (:inherit bold :foreground "#bc6ec5"))))
 '(popup-enu-selection-face ((((class color) (min-colors 89)) (:background "#5e5079" :foreground "#b2b2b2"))))
 '(popup-face ((((class color) (min-colors 89)) (:background "#34323e" :foreground "#9a9aba"))))
 '(popup-isearch-match ((((class color) (min-colors 89)) (:inherit match))))
 '(popup-menu-face ((((class color) (min-colors 89)) (:background "#34323e" :foreground "#b2b2b2"))))
 '(popup-menu-mouse-face ((((class color) (min-colors 89)) (:inherit highlight))))
 '(popup-scroll-bar-background-face ((((class color) (min-colors 89)) (:background "#212026"))))
 '(popup-scroll-bar-foreground-face ((((class color) (min-colors 89)) (:background "#5d4d7a"))))
 '(popup-tip-face ((((class color) (min-colors 89)) (:background "#5e5079" :foreground "#b2b2b2" :bold nil :italic nil :underline nil))))
 '(powerline-active1 ((((class color) (min-colors 89)) (:background "#5d4d7a" :foreground "#b2b2b2"))))
 '(powerline-active2 ((((class color) (min-colors 89)) (:background "#5d4d7a" :foreground "#b2b2b2"))))
 '(powerline-inactive1 ((((class color) (min-colors 89)) (:background "#212026" :foreground "#b2b2b2"))))
 '(powerline-inactive2 ((((class color) (min-colors 89)) (:background "#212026" :foreground "#b2b2b2"))))
 '(rainbow-delimiters-depth-1-face ((((class color) (min-colors 89)) :foreground "#4f97d7")))
 '(rainbow-delimiters-depth-2-face ((((class color) (min-colors 89)) :foreground "#bc6ec5")))
 '(rainbow-delimiters-depth-3-face ((((class color) (min-colors 89)) :foreground "#2d9574")))
 '(rainbow-delimiters-depth-4-face ((((class color) (min-colors 89)) :foreground "#67b11d")))
 '(rainbow-delimiters-depth-5-face ((((class color) (min-colors 89)) :foreground "#b1951d")))
 '(rainbow-delimiters-depth-6-face ((((class color) (min-colors 89)) :foreground "#4f97d7")))
 '(rainbow-delimiters-depth-7-face ((((class color) (min-colors 89)) :foreground "#bc6ec5")))
 '(rainbow-delimiters-depth-8-face ((((class color) (min-colors 89)) :foreground "#2d9574")))
 '(rainbow-delimiters-mismatched-face ((((class color) (min-colors 89)) :foreground "#e0211d" :overline t)))
 '(rainbow-delimiters-unmatched-face ((((class color) (min-colors 89)) :foreground "#e0211d" :overline t)))
 '(rcirc-bright-nick ((((class color) (min-colors 89)) (:background "#293235" :foreground "#28def0"))))
 '(rcirc-dim-nick ((((class color) (min-colors 89)) (:foreground "#686868"))))
 '(rcirc-keyword ((((class color) (min-colors 89)) (:background "#29422d" :foreground "#67b11d"))))
 '(rcirc-timestamp ((((class color) (min-colors 89)) (:foreground "#4f97d7"))))
 '(rcirc-track-keyword ((((class color) (min-colors 89)) (:background "#67b11d" :foreground "gray8"))))
 '(rcirc-url ((((class color) (min-colors 89)) (:inherit link))))
 '(sh-heredoc ((((class color) (min-colors 89)) :foreground "#2d9574")))
 '(sh-quoted-exec ((((class color) (min-colors 89)) :foreground "#bc6ec5")))
 '(shm-current-face ((((class color) (min-colors 89)) (:background "#29422d"))))
 '(shm-quarantine-face ((((class color) (min-colors 89)) (:background "#512e31"))))
 '(show-paren-match ((((class color) (min-colors 89)) (:foreground "#86dc2f" :inherit bold :underline t))))
 '(show-paren-match-expression ((((class color) (min-colors 89)) (:background "#29422d"))))
 '(show-paren-mismatch ((((class color) (min-colors 89)) (:foreground "#e0211d" :inherit bold :underline t))))
 '(sp-pair-overlay-face ((((class color) (min-colors 89)) (:background "#444155" :foreground nil))))
 '(sp-show-pair-match-face ((((class color) (min-colors 89)) (:foreground "#86dc2f" :inherit bold :underline t))))
 '(smerge-base ((((class color) (min-colors 89)) (:background "#32322c" :extend t))))
 '(smerge-markers ((((class color) (min-colors 89)) (:background "#34323e" :foreground "#9a9aba" :extend t))))
 '(smerge-mine ((((class color) (min-colors 89)) (:background "#3c2a2c"))))
 '(smerge-other ((((class color) (min-colors 89)) (:background "#293235"))))
 '(smerge-refined-added ((((class color) (min-colors 89)) (:background "#29422d" :foreground "#67b11d"))))
 '(smerge-refined-changed ((((class color) (min-colors 89)) (:background "#2d4252" :foreground "#4f97d7"))))
 '(smerge-refined-removed ((((class color) (min-colors 89)) (:background "#512e31" :foreground "#f2241f"))))
 '(solaire-default-face ((((class color) (min-colors 89)) (:inherit default :background "#212026"))))
 '(solaire-minibuffer-face ((((class color) (min-colors 89)) (:inherit default :background "#212026"))))
 '(solaire-hl-line-face ((((class color) (min-colors 89)) (:inherit hl-line :background "gray8"))))
 '(solaire-org-hide-face ((((class color) (min-colors 89)) (:inherit org-hide :background "#212026"))))
 '(spaceline-flycheck-error ((((class color) (min-colors 89)) (:foreground "#e0211d"))))
 '(spaceline-flycheck-info ((((class color) (min-colors 89)) (:foreground "#4f97d7"))))
 '(spaceline-flycheck-warning ((((class color) (min-colors 89)) (:foreground "#dc752f"))))
 '(spaceline-python-venv ((((class color) (min-colors 89)) (:foreground "#c56ec3"))))
 '(spacemacs-transient-state-title-face ((((class color) (min-colors 89)) (:background nil :foreground "#c56ec3" :box nil :inherit bold))))
 '(swiper-line-face ((((class color) (min-colors 89)) (:background "#444155" :inherit bold))))
 '(swiper-match-face-1 ((((class color) (min-colors 89)) (:inherit bold))))
 '(swiper-match-face-2 ((((class color) (min-colors 89)) (:foreground "#4f97d7" :underline t))))
 '(swiper-match-face-3 ((((class color) (min-colors 89)) (:foreground "#b1951d" :underline t))))
 '(swiper-match-face-4 ((((class color) (min-colors 89)) (:foreground "#67b11d" :underline t))))
 '(tabbar-button ((((class color) (min-colors 89)) (:inherit tabbar-default))))
 '(tabbar-button-highlight ((((class color) (min-colors 89)) (:inherit tabbar-default))))
 '(tabbar-default ((((class color) (min-colors 89)) (:background "gray8" :foreground "#4f97d7" :height 0.9))))
 '(tabbar-highlight ((((class color) (min-colors 89)) (:underline t))))
 '(tabbar-selected ((((class color) (min-colors 89)) (:inherit tabbar-default :foreground "#bc6ec5" :weight bold))))
 '(tabbar-selected-modified ((((class color) (min-colors 89)) (:inherit tabbar-default :foreground "#f2241f" :weight bold))))
 '(tabbar-separator ((((class color) (min-colors 89)) (:inherit tabbar-default))))
 '(tabbar-unselected ((((class color) (min-colors 89)) (:inherit tabbar-default :background "gray8" :slant italic :weight light))))
 '(tabbar-unselected-modified ((((class color) (min-colors 89)) (:inherit tabbar-unselected :background "gray8" :foreground "#f2241f"))))
 '(term ((((class color) (min-colors 89)) (:foreground "#b2b2b2" :background "gray8"))))
 '(term-color-black ((((class color) (min-colors 89)) (:foreground "#0a0814" :background "#0a0814"))))
 '(term-color-blue ((((class color) (min-colors 89)) (:foreground "#4f97d7" :background "#4f97d7"))))
 '(term-color-cyan ((((class color) (min-colors 89)) (:foreground "#28def0" :background "#28def0"))))
 '(term-color-green ((((class color) (min-colors 89)) (:foreground "#67b11d" :background "#67b11d"))))
 '(term-color-magenta ((((class color) (min-colors 89)) (:foreground "#a31db1" :background "#a31db1"))))
 '(term-color-red ((((class color) (min-colors 89)) (:foreground "#f2241f" :background "#f2241f"))))
 '(term-color-white ((((class color) (min-colors 89)) (:foreground "#b2b2b2" :background "#b2b2b2"))))
 '(term-color-yellow ((((class color) (min-colors 89)) (:foreground "#b1951d" :background "#b1951d"))))
 '(vterm-color-default ((((class color) (min-colors 89)) (:foreground "#b2b2b2" :background "gray8"))))
 '(vterm-color-black ((t (:background "dim gray" :foreground "dim gray"))))
 '(vterm-color-blue ((((class color) (min-colors 89)) (:foreground "#4f97d7" :background "#4f97d7"))))
 '(vterm-color-cyan ((((class color) (min-colors 89)) (:foreground "#28def0" :background "#28def0"))))
 '(vterm-color-green ((((class color) (min-colors 89)) (:foreground "#67b11d" :background "#67b11d"))))
 '(vterm-color-magenta ((((class color) (min-colors 89)) (:foreground "#a31db1" :background "#a31db1"))))
 '(vterm-color-red ((((class color) (min-colors 89)) (:foreground "#f2241f" :background "#f2241f"))))
 '(vterm-color-white ((((class color) (min-colors 89)) (:foreground "#b2b2b2" :background "#b2b2b2"))))
 '(vterm-color-yellow ((((class color) (min-colors 89)) (:foreground "#b1951d" :background "#b1951d"))))
 '(tide-hl-identifier-face ((((class color) (min-colors 89)) (:foreground "#b1951d" :background "#32322c"))))
 '(treemacs-git-added-face ((((class color) (min-colors 89)) (:foreground "#67b11d" :background "#293235"))))
 '(treemacs-git-conflict-face ((((class color) (min-colors 89)) (:foreground "#f2241f" :background "#3c2a2c"))))
 '(treemacs-git-ignored-face ((((class color) (min-colors 89)) (:foreground "#b1951d"))))
 '(treemacs-git-modified-face ((((class color) (min-colors 89)) (:foreground "#4f97d7" :background "#293239"))))
 '(treemacs-git-untracked-face ((((class color) (min-colors 89)) (:foreground "#2d9574" :background "#293235"))))
 '(tab-bar ((((class color) (min-colors 89)) (:foreground "#b2b2b2" :background "gray8"))))
 '(tab-bar-tab ((((class color) (min-colors 89)) (:foreground "#b2b2b2" :background "gray8" :weight bold))))
 '(tab-bar-tab-inactive ((((class color) (min-colors 89)) (:foreground "#686868" :background "#212026" :weight light))))
 '(tab-line ((((class color) (min-colors 89)) (:foreground "#b2b2b2" :background "gray8"))))
 '(tab-line-tab-current ((((class color) (min-colors 89)) (:foreground "#b2b2b2" :background "gray8" :weight bold))))
 '(tab-line-tab-inactive ((((class color) (min-colors 89)) (:foreground "#686868" :background "#212026" :weight light))))
 '(web-mode-builtin-face ((((class color) (min-colors 89)) (:inherit font-lock-builtin-face))))
 '(web-mode-comment-face ((((class color) (min-colors 89)) (:inherit font-lock-comment-face))))
 '(web-mode-constant-face ((((class color) (min-colors 89)) (:inherit font-lock-constant-face))))
 '(web-mode-current-element-highlight-face ((((class color) (min-colors 89)) (:background "#100a14"))))
 '(web-mode-doctype-face ((((class color) (min-colors 89)) (:inherit font-lock-comment-face))))
 '(web-mode-function-name-face ((((class color) (min-colors 89)) (:inherit font-lock-function-name-face))))
 '(web-mode-html-attr-name-face ((((class color) (min-colors 89)) (:foreground "#bc6ec5"))))
 '(web-mode-html-attr-value-face ((((class color) (min-colors 89)) (:foreground "#4f97d7"))))
 '(web-mode-html-tag-face ((((class color) (min-colors 89)) (:foreground "#4f97d7"))))
 '(web-mode-keyword-face ((((class color) (min-colors 89)) (:foreground "#4f97d7"))))
 '(web-mode-string-face ((((class color) (min-colors 89)) (:foreground "#2d9574"))))
 '(web-mode-symbol-face ((((class color) (min-colors 89)) (:foreground "#ce537a"))))
 '(web-mode-type-face ((((class color) (min-colors 89)) (:inherit font-lock-type-face))))
 '(web-mode-warning-face ((((class color) (min-colors 89)) (:inherit font-lock-warning-face))))
 '(which-key-command-description-face ((((class color) (min-colors 89)) (:foreground "#b2b2b2"))))
 '(which-key-group-description-face ((((class color) (min-colors 89)) (:foreground "#4f97d7"))))
 '(which-key-key-face ((((class color) (min-colors 89)) (:foreground "#bc6ec5" :inherit bold))))
 '(which-key-separator-face ((((class color) (min-colors 89)) (:background nil :foreground "#2d9574"))))
 '(which-key-special-key-face ((((class color) (min-colors 89)) (:background "#bc6ec5" :foreground "gray8"))))
 '(which-func ((((class color) (min-colors 89)) (:foreground "#bc6ec5"))))
 '(whitespace-empty ((((class color) (min-colors 89)) (:background nil :foreground "#b1951d"))))
 '(whitespace-indentation ((((class color) (min-colors 89)) (:background nil :foreground "#dc752f"))))
 '(whitespace-line ((((class color) (min-colors 89)) (:background nil :foreground "#c56ec3"))))
 '(whitespace-newline ((((class color) (min-colors 89)) (:background nil :foreground "#c56ec3"))))
 '(whitespace-space ((((class color) (min-colors 89)) (:background nil :foreground "#5d4d7a"))))
 '(whitespace-space-after-tab ((((class color) (min-colors 89)) (:background nil :foreground "#b1951d"))))
 '(whitespace-space-before-tab ((((class color) (min-colors 89)) (:background nil :foreground "#b1951d"))))
 '(whitespace-tab ((((class color) (min-colors 89)) (:background nil :foreground "#5d4d7a"))))
 '(whitespace-trailing ((((class color) (min-colors 89)) (:background "#e0211d" :foreground "#dc752f"))))
 '(ffap ((((class color) (min-colors 89)) (:foreground "#b2b2b2"))))
 '(flx-highlight-face ((((class color) (min-colors 89)) (:foreground "#c56ec3" :underline nil))))
 '(icompletep-determined ((((class color) (min-colors 89)) :foreground "#4f97d7")))
 '(js2-external-variable ((((class color) (min-colors 89)) (:foreground "#c56ec3"))))
 '(js2-function-param ((((class color) (min-colors 89)) (:foreground "#a45bad"))))
 '(js2-jsdoc-html-tag-delimiter ((((class color) (min-colors 89)) (:foreground "#2d9574"))))
 '(js2-jsdoc-html-tag-name ((((class color) (min-colors 89)) (:foreground "#4f97d7"))))
 '(js2-jsdoc-value ((((class color) (min-colors 89)) (:foreground "#2d9574"))))
 '(js2-private-function-call ((((class color) (min-colors 89)) (:foreground "#a45bad"))))
 '(js2-private-member ((((class color) (min-colors 89)) (:foreground "#b2b2b2"))))
 '(js3-error-face ((((class color) (min-colors 89)) (:underline "#dc752f"))))
 '(js3-external-variable-face ((((class color) (min-colors 89)) (:foreground "#7590db"))))
 '(js3-function-param-face ((((class color) (min-colors 89)) (:foreground "#4f97d7"))))
 '(js3-instance-member-face ((((class color) (min-colors 89)) (:foreground "#a45bad"))))
 '(js3-jsdoc-tag-face ((((class color) (min-colors 89)) (:foreground "#4f97d7"))))
 '(js3-warning-face ((((class color) (min-colors 89)) (:underline "#4f97d7"))))
 '(slime-repl-inputed-output-face ((((class color) (min-colors 89)) (:foreground "#c56ec3"))))
 '(trailing-whitespace ((((class color) (min-colors 89)) :foreground nil :background "#e0211d")))
 '(undo-tree-visualizer-current-face ((((class color) (min-colors 89)) :foreground "#4f97d7")))
 '(undo-tree-visualizer-default-face ((((class color) (min-colors 89)) :foreground "#b2b2b2")))
 '(undo-tree-visualizer-register-face ((((class color) (min-colors 89)) :foreground "#c56ec3")))
 '(undo-tree-visualizer-unmodified-face ((((class color) (min-colors 89)) :foreground "#7590db")))
 '(default ((((class color) (min-colors 89)) (:background "gray8" :foreground "#b2b2b2")))))

(provide-theme 'my-spacemacs-dark)
